# Copyright (c) 2026 The ZMK Contributors
# SPDX-License-Identifier: MIT

# Enable the OLED display
CONFIG_ZMK_DISPLAY=y

# dongle-display module widgets
CONFIG_ZMK_DONGLE_DISPLAY_DONGLE_BATTERY=y
CONFIG_ZMK_DONGLE_DISPLAY_MAC_MODIFIERS=y
CONFIG_ZMK_DONGLE_DISPLAY_BONGO_CAT=n
CONFIG_ZMK_DONGLE_DISPLAY_WPM=n

# Stronger BLE TX power for the peripheral links
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y
